name = "tebex-js-example-worker"

[vars]
HEADLESS_API_ENDPOINT = "https://headless.tebex.io"
ACCOUNT_ID = "t6c9-0927595131662ac732bf5f1d9bd5570482db5316"
PACKAGE_IDS = "5987844,5987895"
USERNAME = "notch"